sudo: false
language: node_js
node_js:
  - 6
  - 5
  - 4
matrix:
  fast_finish: true
os:
  - linux
  - osx
cache:
  directories:
    - node_modules
notifications:
  email: false
branches:
  only:
    - master
    - /^greenkeeper.*$/
  except:
    - gh-pages
before_install:
  - git config --global user.name "$GH_USER_NAME"
  - git config --global user.email "$GH_USER_EMAIL"
script:
  - yarn run clean
  - yarn run eslint
  - yarn run cover
  - yarn run test-cli
after_script:
  - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && .travis/after-all.sh || false'
