sudo: false
language: node_js
node_js:
  - 8
  - 7
  - 6
  - 5
os:
  - linux
  - osx
cache:
  directories:
    - node_modules
    - $HOME/.yarn-cache
notifications:
  email: false
branches:
  only:
    - master
    - /^greenkeeper/.*$/
  except:
    - gh-pages
script:
  - yarn run clean
  - yarn run eslint
  - yarn run cover
  - yarn run build
jobs:
  fast_finish: true
  include:
    - stage: release
      node_js: 8
      deploy:
        skip_cleanup: true
        provider: script
        script: yarn run codeclimate && yarn run semantic-release
      on:
        branch: master
