version: '{build}'
build: off
deploy: off
cache:
  - node_modules -> package.json
  - '%APPDATA%\npm-cache'
branches:
  only:
    - master
  except:
    - gh-pages
matrix:
  fast_finish: true
environment:
  matrix:
    - nodejs_version: 5
    - nodejs_version: 4
platform:
  - x86
  - x64
install:
  - ps: Install-Product node $env:nodejs_version
  - npm prune
  - npm install
test_script:
  - node --version
  - npm --version
  - cmd: npm test
